name: animated_view_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:     
         - assets/
         - assets/images/
  fonts:
    - family: SidewareTrial
      fonts:
        - asset: assets/fonts/SidewareTrial.otf
    - family: CourierNew
      fonts:
        - asset: assets/fonts/CourierNewRegular.ttf